[[libsndfile]]
arch = "aarch64"
git-tree-sha1 = "fdd2ed8f3dcbdeba1a06605cb2f1274ab599cc64"
os = "macos"

    [[libsndfile.download]]
    sha256 = "b2aaf49be1a4f5fe165f6e8341a49cbdc7a9b6f391608618f79f8b0e01f5ee6b"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+2/libsndfile.v1.0.31.aarch64-apple-darwin.tar.gz"
[[libsndfile]]
arch = "aarch64"
git-tree-sha1 = "f12a6b98693cc06ad24c79b315d3390665d494ac"
libc = "glibc"
os = "linux"

    [[libsndfile.download]]
    sha256 = "5f8fe56bd4f20e68818d4a9b9daa1393600729e0b8b3bb9477ed5ea1dbd5dd1a"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+2/libsndfile.v1.0.31.aarch64-linux-gnu.tar.gz"
[[libsndfile]]
arch = "aarch64"
git-tree-sha1 = "840f837854f0c89690317d2da04bafe5d8c117dc"
libc = "musl"
os = "linux"

    [[libsndfile.download]]
    sha256 = "4a73e64f65f6b37e9b3dc490b88cd1894f24be4c01672d11036fd3b7dbdf1c7a"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+2/libsndfile.v1.0.31.aarch64-linux-musl.tar.gz"
[[libsndfile]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6d035a031d014fe576796fa508aeef098e23c476"
libc = "glibc"
os = "linux"

    [[libsndfile.download]]
    sha256 = "7e66fcda75f9644e2974dc1cf076ef511e93c4a0793f344de792b9bcb1172f9a"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+2/libsndfile.v1.0.31.armv6l-linux-gnueabihf.tar.gz"
[[libsndfile]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "30a1fc628f82d02c21fe3fa3e8e670886698cc62"
libc = "musl"
os = "linux"

    [[libsndfile.download]]
    sha256 = "b551b4be09f1bcf6dc71f9ca50406c405ea537b01abb00c0c1eee882e82da905"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+2/libsndfile.v1.0.31.armv6l-linux-musleabihf.tar.gz"
[[libsndfile]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3a2a9e2cf796f3911fd1f6e3d942fc289f904507"
libc = "glibc"
os = "linux"

    [[libsndfile.download]]
    sha256 = "f959f1b38285aa5b4cc99ab25a414b0b04730d82fc0cbb2dbffec14e0d836d92"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+2/libsndfile.v1.0.31.armv7l-linux-gnueabihf.tar.gz"
[[libsndfile]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "348a0c41a090595e8d40da86ee4aa2744bdf2865"
libc = "musl"
os = "linux"

    [[libsndfile.download]]
    sha256 = "bb635a44ccab5f99d0cda468d04b79283c65adefa4ce54fe67e48c7263a7637c"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+2/libsndfile.v1.0.31.armv7l-linux-musleabihf.tar.gz"
[[libsndfile]]
arch = "i686"
git-tree-sha1 = "7539ae69f9b8828122e6798dacfbe93c8a9bf3cf"
libc = "glibc"
os = "linux"

    [[libsndfile.download]]
    sha256 = "51d668f0d03ea84aea72e20866dc59da02dcdc03c48246e2646281b81ee7af17"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+2/libsndfile.v1.0.31.i686-linux-gnu.tar.gz"
[[libsndfile]]
arch = "i686"
git-tree-sha1 = "a8b86bbc5a6f861c022fcbc9fc456bd936c62283"
libc = "musl"
os = "linux"

    [[libsndfile.download]]
    sha256 = "3942d14637bbd5ed32d3a7e44999fa569acc21729f54a9fa81d12c7ffec24f98"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+2/libsndfile.v1.0.31.i686-linux-musl.tar.gz"
[[libsndfile]]
arch = "i686"
git-tree-sha1 = "3d3afbc9b03c6a69d7d2b9dd704947329edabcdd"
os = "windows"

    [[libsndfile.download]]
    sha256 = "4f5141cfe996775e484837211414405593a147743afb94d5766c75fe1cab851d"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+2/libsndfile.v1.0.31.i686-w64-mingw32.tar.gz"
[[libsndfile]]
arch = "powerpc64le"
git-tree-sha1 = "2928b784d7c6b0b04e7d011da6038f4e96a7af1d"
libc = "glibc"
os = "linux"

    [[libsndfile.download]]
    sha256 = "c1aa23263cb9660ff101688542c503f40c7b841a9bcdc79491520da3afd21ad6"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+2/libsndfile.v1.0.31.powerpc64le-linux-gnu.tar.gz"
[[libsndfile]]
arch = "x86_64"
git-tree-sha1 = "91ae2ba5a0c46c853339a397710c1f59d19b8b5c"
os = "macos"

    [[libsndfile.download]]
    sha256 = "3b87c4772c262aec0f6d33587e0d660a54ce9a88956f993531ccdf46296cc7ac"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+2/libsndfile.v1.0.31.x86_64-apple-darwin.tar.gz"
[[libsndfile]]
arch = "x86_64"
git-tree-sha1 = "a6d417c295ba04622cd94f9530664c767ce3dbcd"
libc = "glibc"
os = "linux"

    [[libsndfile.download]]
    sha256 = "4cfc415ce5357d0266e40d423aa07efd42809d3c4cafd061387a3bf95a4f7dab"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+2/libsndfile.v1.0.31.x86_64-linux-gnu.tar.gz"
[[libsndfile]]
arch = "x86_64"
git-tree-sha1 = "ec1913fbe9a0c29af288f7f997c57af39dd798ee"
libc = "musl"
os = "linux"

    [[libsndfile.download]]
    sha256 = "98707c73cdbfeebab32ec34dab037025c10c0136069f0ff69a408cf31b53c204"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+2/libsndfile.v1.0.31.x86_64-linux-musl.tar.gz"
[[libsndfile]]
arch = "x86_64"
git-tree-sha1 = "3878d72cd56870ccf72014dcb25858caca3a3fcb"
os = "freebsd"

    [[libsndfile.download]]
    sha256 = "8e56ba7ac1b7e23f4bacf9accb409045ed0e612fa1da4c0460065ca5f80f1d5e"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+2/libsndfile.v1.0.31.x86_64-unknown-freebsd.tar.gz"
[[libsndfile]]
arch = "x86_64"
git-tree-sha1 = "d47144117f21db09ca9658dcd2767bed9d6ff67b"
os = "windows"

    [[libsndfile.download]]
    sha256 = "71a425bfd610df2a9a429942075e2fb97f35312b43e03443ef55eb49a7dd80a6"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+2/libsndfile.v1.0.31.x86_64-w64-mingw32.tar.gz"
