[[libsndfile]]
arch = "aarch64"
git-tree-sha1 = "3cdc8469a24076d62b79418b662b1ba35b66d5fe"
os = "macos"

    [[libsndfile.download]]
    sha256 = "2d649efe1efbfc4a68fc6cc227ee795a1a1e54e2e082e6bb1dddd74f633229c4"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+0/libsndfile.v1.0.31.aarch64-apple-darwin.tar.gz"
[[libsndfile]]
arch = "aarch64"
git-tree-sha1 = "8618994d411b559277fd0968d2575a7240006dfd"
libc = "glibc"
os = "linux"

    [[libsndfile.download]]
    sha256 = "8121400bb85d7abe11a827a76bafd9c48522afab1372cf69ad67f40f9d655f13"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+0/libsndfile.v1.0.31.aarch64-linux-gnu.tar.gz"
[[libsndfile]]
arch = "aarch64"
git-tree-sha1 = "95ed1081269624686fd5db3a9e76de6d1f93470d"
libc = "musl"
os = "linux"

    [[libsndfile.download]]
    sha256 = "2c1c22b0fb910b0d65b7300b9ff6c39f38b815fcd4f308ee286c9a42652a5c6d"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+0/libsndfile.v1.0.31.aarch64-linux-musl.tar.gz"
[[libsndfile]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "484cc68d96cda4796f9a7dcdd062ef6765cff1c8"
libc = "glibc"
os = "linux"

    [[libsndfile.download]]
    sha256 = "40baf00efefbb3002be0d232eee2968f357874a6c12cb504cfd246d54e619d19"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+0/libsndfile.v1.0.31.armv6l-linux-gnueabihf.tar.gz"
[[libsndfile]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3a65f60c3f9630f3469c671dfe2a101b3eb92461"
libc = "musl"
os = "linux"

    [[libsndfile.download]]
    sha256 = "95e1fe4fc08d7ef1b4c173d53db6af98a5fdf5727554ae8a0a466fdc967426b0"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+0/libsndfile.v1.0.31.armv6l-linux-musleabihf.tar.gz"
[[libsndfile]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ed3b486a6952819d0a5fba34c92392cbb473b03f"
libc = "glibc"
os = "linux"

    [[libsndfile.download]]
    sha256 = "4bc51c36758da3d997a464255e1a2b2580953d1e76abc7e14593a8a9107586bc"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+0/libsndfile.v1.0.31.armv7l-linux-gnueabihf.tar.gz"
[[libsndfile]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2e05cd6442c18c0834040d3fdfddcf6aeecb300b"
libc = "musl"
os = "linux"

    [[libsndfile.download]]
    sha256 = "5b9a0bfeee59fe97d27f37ee676d45a55fdfc8ed729eb047a776882df2018877"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+0/libsndfile.v1.0.31.armv7l-linux-musleabihf.tar.gz"
[[libsndfile]]
arch = "i686"
git-tree-sha1 = "9d690021c051e66a0dc522c19f7b46d44bc75437"
libc = "glibc"
os = "linux"

    [[libsndfile.download]]
    sha256 = "679ed9a8b4f21117ab3491d7d6c94d8979a6539bdb79bb6771c3224d3137eb6a"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+0/libsndfile.v1.0.31.i686-linux-gnu.tar.gz"
[[libsndfile]]
arch = "i686"
git-tree-sha1 = "d54ca3926b0cb6ef9ec937863818a3ce93ad464f"
libc = "musl"
os = "linux"

    [[libsndfile.download]]
    sha256 = "e2d78d5fa449b15cf05854583fdfb6972aec09fcdf1362e0dd43dfc0d6add89a"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+0/libsndfile.v1.0.31.i686-linux-musl.tar.gz"
[[libsndfile]]
arch = "i686"
git-tree-sha1 = "ffcfe859c4413d6e4c241416ac13c56224c0a28d"
os = "windows"

    [[libsndfile.download]]
    sha256 = "33e57e0dff411b438bca9c541d4faaf35dd58d6e130c340b2e1639bdf8ca1989"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+0/libsndfile.v1.0.31.i686-w64-mingw32.tar.gz"
[[libsndfile]]
arch = "powerpc64le"
git-tree-sha1 = "86ea873bba226ba718021260b5d874983dda83ec"
libc = "glibc"
os = "linux"

    [[libsndfile.download]]
    sha256 = "6a598b3928423571fe462771b257961ea4ab829fe45e0d91078961a780772515"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+0/libsndfile.v1.0.31.powerpc64le-linux-gnu.tar.gz"
[[libsndfile]]
arch = "x86_64"
git-tree-sha1 = "60685409c9fe036a07e78739f805eeffb6c968d8"
os = "macos"

    [[libsndfile.download]]
    sha256 = "9fe0dcdffaf7500c641d70d940868b7d044a547dcce5ba6f4dbd45bd668ca2b4"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+0/libsndfile.v1.0.31.x86_64-apple-darwin.tar.gz"
[[libsndfile]]
arch = "x86_64"
git-tree-sha1 = "9ad041ba40d03599a08ae2c24366ae9e9ee9d4ee"
libc = "glibc"
os = "linux"

    [[libsndfile.download]]
    sha256 = "4a2f7da2ca9e5406f136e8c381a0e84dcd2216894df1ea52e681883182cdf8cd"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+0/libsndfile.v1.0.31.x86_64-linux-gnu.tar.gz"
[[libsndfile]]
arch = "x86_64"
git-tree-sha1 = "c206e78e63d12930c422bb492a1935a2ca6ab5b4"
libc = "musl"
os = "linux"

    [[libsndfile.download]]
    sha256 = "bd38c9bbda0eca9e151b03923c85b6b2ed3cfe12c6ede636f77e2a56ae129408"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+0/libsndfile.v1.0.31.x86_64-linux-musl.tar.gz"
[[libsndfile]]
arch = "x86_64"
git-tree-sha1 = "53a4c3f7659a6284680278f07974fa9cbad0bf7f"
os = "freebsd"

    [[libsndfile.download]]
    sha256 = "bbdae301a9ec63808ae135d750eede7cca0bdd3d1a10f5676520a5069f445159"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+0/libsndfile.v1.0.31.x86_64-unknown-freebsd.tar.gz"
[[libsndfile]]
arch = "x86_64"
git-tree-sha1 = "edebf433593a5f5c571c460d408bf2d62169353a"
os = "windows"

    [[libsndfile.download]]
    sha256 = "cd4175071bd07523eb56b5851bc5c70d398f6697c03bf5b21a7871f469427dc3"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.31+0/libsndfile.v1.0.31.x86_64-w64-mingw32.tar.gz"
