[[libsndfile]]
arch = "aarch64"
git-tree-sha1 = "3cb0f28e729c8c3cbb653b3558306f92865e9032"
libc = "glibc"
os = "linux"

    [[libsndfile.download]]
    sha256 = "70eb79d7f2ab41c010ac2178ad89b0ece172c01b4491f8ae485f86f7ef1c55f9"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.28+2/libsndfile.v1.0.28.aarch64-linux-gnu.tar.gz"
[[libsndfile]]
arch = "aarch64"
git-tree-sha1 = "eed2b1c72a493f4d2d77cc75f2c6f10c3b9e03f3"
libc = "musl"
os = "linux"

    [[libsndfile.download]]
    sha256 = "4bfb9e3527da9a51ea1612ce36843538a2f8cba3fdf754669c622f6ba7058fd5"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.28+2/libsndfile.v1.0.28.aarch64-linux-musl.tar.gz"
[[libsndfile]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a737a2df6c497a558b7a777d2321b2def295b415"
libc = "glibc"
os = "linux"

    [[libsndfile.download]]
    sha256 = "940460c102fae90ad41d6256bb7c40d8dce79465cf60fad0e08ad84ce4c8391a"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.28+2/libsndfile.v1.0.28.armv7l-linux-gnueabihf.tar.gz"
[[libsndfile]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "31da33408bd89318be4824bd1c69fb5263755ebf"
libc = "musl"
os = "linux"

    [[libsndfile.download]]
    sha256 = "44c4b6eb5faeeebd15d5e119407cf3015498815039dcd9227708c4412a47045d"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.28+2/libsndfile.v1.0.28.armv7l-linux-musleabihf.tar.gz"
[[libsndfile]]
arch = "i686"
git-tree-sha1 = "4938d524c2abe6fd3bbba8d891e1d733d9108940"
libc = "glibc"
os = "linux"

    [[libsndfile.download]]
    sha256 = "ea69b2e677cbfa0ff4c8f23516fe37c8afc84e10422a85cbc180966204f6de08"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.28+2/libsndfile.v1.0.28.i686-linux-gnu.tar.gz"
[[libsndfile]]
arch = "i686"
git-tree-sha1 = "7856e4207b785f77a68cbfa30256a971e1356a38"
libc = "musl"
os = "linux"

    [[libsndfile.download]]
    sha256 = "b2d0bd64f34068b02c939fe2009372a44fd49ec412241c82535fd518a898cba0"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.28+2/libsndfile.v1.0.28.i686-linux-musl.tar.gz"
[[libsndfile]]
arch = "i686"
git-tree-sha1 = "dd7be8911bf08c8d01d49b9a0575038d1b253954"
os = "windows"

    [[libsndfile.download]]
    sha256 = "12a59d82bff93e2ea44cb3e4c4973fce4e60f442317892b7747f749d30a56439"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.28+2/libsndfile.v1.0.28.i686-w64-mingw32.tar.gz"
[[libsndfile]]
arch = "powerpc64le"
git-tree-sha1 = "a5d523dbd20457b58e372270a8f80a648453db70"
libc = "glibc"
os = "linux"

    [[libsndfile.download]]
    sha256 = "3ce578820d8f71dcea80e72e43b28c81257dccb012e94c96acf49ef844cbc184"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.28+2/libsndfile.v1.0.28.powerpc64le-linux-gnu.tar.gz"
[[libsndfile]]
arch = "x86_64"
git-tree-sha1 = "11d68be2edd426af28d04d462797ce93049fcba9"
os = "macos"

    [[libsndfile.download]]
    sha256 = "c6d40f26f03b401f3bd26d0b46f6d94a6a59bec7671b9db5c5ae4919dfbc4ea8"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.28+2/libsndfile.v1.0.28.x86_64-apple-darwin.tar.gz"
[[libsndfile]]
arch = "x86_64"
git-tree-sha1 = "dde4d15181b505f567c839116c9a9317e78276eb"
libc = "glibc"
os = "linux"

    [[libsndfile.download]]
    sha256 = "9ead0e689efebcb2cc2e8e626521610fbd72e32d1eab29c3619e543cbc2b1a92"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.28+2/libsndfile.v1.0.28.x86_64-linux-gnu.tar.gz"
[[libsndfile]]
arch = "x86_64"
git-tree-sha1 = "974d2191b849bdf66cc3df16ce0a09c1615335ad"
libc = "musl"
os = "linux"

    [[libsndfile.download]]
    sha256 = "1b911fbf9cf660f6d2c9b3d646e6aa92cefa328d264a1f1daa04e0ddaf1e2b3d"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.28+2/libsndfile.v1.0.28.x86_64-linux-musl.tar.gz"
[[libsndfile]]
arch = "x86_64"
git-tree-sha1 = "b536386ce47553bba5ca7e83acfe380eb28e7a7c"
os = "freebsd"

    [[libsndfile.download]]
    sha256 = "b1b3fd678bf4f213e6e6f0f00f7a3fad8881b82bb6d926ff606a4ac87dbfbaca"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.28+2/libsndfile.v1.0.28.x86_64-unknown-freebsd.tar.gz"
[[libsndfile]]
arch = "x86_64"
git-tree-sha1 = "5386e7a4eb8f72f57039df5bffa2e79ba5c20c22"
os = "windows"

    [[libsndfile.download]]
    sha256 = "a2e2423398da6027496898406b54227f0cebb7c7abaf5c1fa4e53189d82ae352"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.28+2/libsndfile.v1.0.28.x86_64-w64-mingw32.tar.gz"
