[[libsndfile]]
arch = "aarch64"
git-tree-sha1 = "cf07d9bdc9f7db747ad81ff5c5eb385e0d1cd757"
os = "macos"

    [[libsndfile.download]]
    sha256 = "7857b78cf7b9420acf347e615800f102b3ec7ff6f4bdf060b6fd4713d8231477"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.1.0+0/libsndfile.v1.1.0.aarch64-apple-darwin.tar.gz"
[[libsndfile]]
arch = "aarch64"
git-tree-sha1 = "965ca4e302cbe34be974f5b3d012a535a8459b4d"
libc = "glibc"
os = "linux"

    [[libsndfile.download]]
    sha256 = "187ecaf195b2e0edee7a69bd328e2fc1094380ac89045eecdbc0dcf88b7a7a89"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.1.0+0/libsndfile.v1.1.0.aarch64-linux-gnu.tar.gz"
[[libsndfile]]
arch = "aarch64"
git-tree-sha1 = "8221258956affa09c3d627f841d19ac94b63efd1"
libc = "musl"
os = "linux"

    [[libsndfile.download]]
    sha256 = "b26dd4b022ef3e8aa0ea8410b7dc5f2d34e7fe27fe5dff2913159c14a6af01f8"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.1.0+0/libsndfile.v1.1.0.aarch64-linux-musl.tar.gz"
[[libsndfile]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e24ca224428f78db2d18359bec1b7d6caecced09"
libc = "glibc"
os = "linux"

    [[libsndfile.download]]
    sha256 = "2456c23a7c03488c405940e20bf5ccee4187bfdd68702e26c6ec63aec1be555c"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.1.0+0/libsndfile.v1.1.0.armv6l-linux-gnueabihf.tar.gz"
[[libsndfile]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "12602287c97bd758d3508ee2fb3bd881d61b9c5b"
libc = "musl"
os = "linux"

    [[libsndfile.download]]
    sha256 = "e1d80aeb892f86f3d2b98e0b3f7b1b92fa5a714888dd283a8370f367e15d649a"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.1.0+0/libsndfile.v1.1.0.armv6l-linux-musleabihf.tar.gz"
[[libsndfile]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e99d1c0ad69637fdb0e107382cc3e6d0aa1dac24"
libc = "glibc"
os = "linux"

    [[libsndfile.download]]
    sha256 = "8ffa1729d13cb33220d8aa544b6a8b5ead0ea479f0332e1412fa764a07e0a99f"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.1.0+0/libsndfile.v1.1.0.armv7l-linux-gnueabihf.tar.gz"
[[libsndfile]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d91ff182821a43a60d4474e56ae5dac3f9ea8411"
libc = "musl"
os = "linux"

    [[libsndfile.download]]
    sha256 = "02a0e33e2ed9325914082c37c7563209a89b3abfba8ba244c5b6968e22bdf30c"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.1.0+0/libsndfile.v1.1.0.armv7l-linux-musleabihf.tar.gz"
[[libsndfile]]
arch = "i686"
git-tree-sha1 = "a954e27d77036ae1a5e6bc791e5db7acdb36da1c"
libc = "glibc"
os = "linux"

    [[libsndfile.download]]
    sha256 = "f0195a77ff277b7f42291ca7833439a2c04c24b2bf3573dc7ed40e8b824c164f"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.1.0+0/libsndfile.v1.1.0.i686-linux-gnu.tar.gz"
[[libsndfile]]
arch = "i686"
git-tree-sha1 = "9b1074e5fd1894d6a907af16687d08cf93fea7d0"
libc = "musl"
os = "linux"

    [[libsndfile.download]]
    sha256 = "125ea43c94ea1fb86d7754e0d8896b39af61e6b36b7f0760863142eb611b41e6"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.1.0+0/libsndfile.v1.1.0.i686-linux-musl.tar.gz"
[[libsndfile]]
arch = "i686"
git-tree-sha1 = "7fe0c42812d06b47ddfc219ef1e8099e7eda0718"
os = "windows"

    [[libsndfile.download]]
    sha256 = "18c6f7618bd0a7aefb241ef095f1966b1c68ac1f432723099f294ae93fbc4c18"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.1.0+0/libsndfile.v1.1.0.i686-w64-mingw32.tar.gz"
[[libsndfile]]
arch = "powerpc64le"
git-tree-sha1 = "c6a2efaad9d093d58fa487f76708aa6504a448cc"
libc = "glibc"
os = "linux"

    [[libsndfile.download]]
    sha256 = "fae603d44c66d0dde7f34cfcfee1781c3bb1108d64c16ddf5cd10e43837a2a98"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.1.0+0/libsndfile.v1.1.0.powerpc64le-linux-gnu.tar.gz"
[[libsndfile]]
arch = "x86_64"
git-tree-sha1 = "edbf205676b744c8aa3121e5acc799212cb2b15a"
os = "macos"

    [[libsndfile.download]]
    sha256 = "6df68465dc7c51a0b85f4334775455e5ee3a7e2113431c80f553c30c1f2967f7"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.1.0+0/libsndfile.v1.1.0.x86_64-apple-darwin.tar.gz"
[[libsndfile]]
arch = "x86_64"
git-tree-sha1 = "ba0c9ca6ea7017a91892a081bf2186bf537f1ef4"
libc = "glibc"
os = "linux"

    [[libsndfile.download]]
    sha256 = "a3f38e5d0cb3f04aaec6af4e9a522140aae8f3c75dedf1d3f0ba9645fbca7907"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.1.0+0/libsndfile.v1.1.0.x86_64-linux-gnu.tar.gz"
[[libsndfile]]
arch = "x86_64"
git-tree-sha1 = "0f3ecbe6bb03c4131ba879ce14b7d7c41d74181a"
libc = "musl"
os = "linux"

    [[libsndfile.download]]
    sha256 = "d7557f8e76a0d23e7035e512cbc51e29cb71dd12cb52760640814670f43131a4"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.1.0+0/libsndfile.v1.1.0.x86_64-linux-musl.tar.gz"
[[libsndfile]]
arch = "x86_64"
git-tree-sha1 = "ea4dcea6db7c294a6ee5c618134a0902c9d4cb2a"
os = "freebsd"

    [[libsndfile.download]]
    sha256 = "8e64289eae7e52c70ae76f24c27c6e45f2abbedd4235a688986b88a6ff7ed6cf"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.1.0+0/libsndfile.v1.1.0.x86_64-unknown-freebsd.tar.gz"
[[libsndfile]]
arch = "x86_64"
git-tree-sha1 = "dfc1495b357f8d23f645bf969f5161ccf04736c7"
os = "windows"

    [[libsndfile.download]]
    sha256 = "e4fd9d9af00582308cd78e5cfc4121f71323d8a049824bedf8d6ea9bf37606de"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.1.0+0/libsndfile.v1.1.0.x86_64-w64-mingw32.tar.gz"
