[[libsndfile]]
arch = "i686"
git-tree-sha1 = "f8f79d70a39d6a737b1f0f4682494ce12a969549"
libc = "musl"
os = "linux"

    [[libsndfile.download]]
    sha256 = "47e60fc2d068f658da708f0a41d78b323a9a63258e0e7cc3b197026d4bbb3bb8"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.28+1/libsndfile.v1.0.28.i686-linux-musl.tar.gz"
[[libsndfile]]
arch = "aarch64"
git-tree-sha1 = "6104faecc54babde3b56ade60b83083cbd69dd66"
libc = "musl"
os = "linux"

    [[libsndfile.download]]
    sha256 = "e40e6d136809e8480a4350ce3cfce0bf6fb0b5f9c3301f41d1e02dbb9f4f918d"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.28+1/libsndfile.v1.0.28.aarch64-linux-musl.tar.gz"
[[libsndfile]]
arch = "i686"
git-tree-sha1 = "2b746c0c9343f1cdb0e68164ecb6e1b8ef39d7ab"
os = "windows"

    [[libsndfile.download]]
    sha256 = "e309ee77c2bc8c312502f8d9ea760c83e67604bd15c07d70f46d8187c697b782"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.28+1/libsndfile.v1.0.28.i686-w64-mingw32.tar.gz"
[[libsndfile]]
arch = "x86_64"
git-tree-sha1 = "70bb0629bc8e97dc7a2853a8d4914ebbba1cc515"
os = "windows"

    [[libsndfile.download]]
    sha256 = "fb6ae186cb70ea062e3c6ebe410b7a42ae835667ccb8a3486f6a442cc0571152"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.28+1/libsndfile.v1.0.28.x86_64-w64-mingw32.tar.gz"
[[libsndfile]]
arch = "armv7l"
git-tree-sha1 = "9f906380896a947be65f3bb66873bf7e7ebca19e"
libc = "glibc"
os = "linux"

    [[libsndfile.download]]
    sha256 = "11be2bd8f9c5585548f61d5e683feff323410b528340c15952821aa70eadf115"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.28+1/libsndfile.v1.0.28.armv7l-linux-gnueabihf.tar.gz"
[[libsndfile]]
arch = "armv7l"
git-tree-sha1 = "82c5f0c9ee0cc815d29e7dbd5257569fd446d57e"
libc = "musl"
os = "linux"

    [[libsndfile.download]]
    sha256 = "08a1a964a29e8afca29fe1d1a12ca361bab811e51be68b69d2a31db434d8208b"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.28+1/libsndfile.v1.0.28.armv7l-linux-musleabihf.tar.gz"
[[libsndfile]]
arch = "i686"
git-tree-sha1 = "c0340d17ca2cd49ffbca82442c5e01a1996d67bd"
libc = "glibc"
os = "linux"

    [[libsndfile.download]]
    sha256 = "2555cefe4e40f5248167e465b6835f6d4bd9ebc90cb8d3382f02a4e9626a3f1b"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.28+1/libsndfile.v1.0.28.i686-linux-gnu.tar.gz"
[[libsndfile]]
arch = "x86_64"
git-tree-sha1 = "ea06742a9e1bede1bcd3659789bedaf6620f2396"
libc = "glibc"
os = "linux"

    [[libsndfile.download]]
    sha256 = "a46f055172b25e80bed8d49b39c64ac1dd21e9726a7b6e354fe0f790dfe49f95"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.28+1/libsndfile.v1.0.28.x86_64-linux-gnu.tar.gz"
[[libsndfile]]
arch = "powerpc64le"
git-tree-sha1 = "492b6e8bc350fa0efdf84b9bd27226622a034876"
libc = "glibc"
os = "linux"

    [[libsndfile.download]]
    sha256 = "9eadccde58c64f54db623785196e4a33355619c07c792a35533ac419ea80e86c"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.28+1/libsndfile.v1.0.28.powerpc64le-linux-gnu.tar.gz"
[[libsndfile]]
arch = "x86_64"
git-tree-sha1 = "4c28a54d00e9b1cb478f7f488e0a4ff645519ac0"
os = "macos"

    [[libsndfile.download]]
    sha256 = "5026009aa9fb7bbbeedc1508bf70c61a14a0c5b8eece2cc634b6b6d072767924"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.28+1/libsndfile.v1.0.28.x86_64-apple-darwin14.tar.gz"
[[libsndfile]]
arch = "aarch64"
git-tree-sha1 = "f1ac702f3abc62f3731142ce8b7a1c65306450b8"
libc = "glibc"
os = "linux"

    [[libsndfile.download]]
    sha256 = "07b2923569b9091d7ee95cb1784a533e07e6c96406ba680c94a6286f29122e27"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.28+1/libsndfile.v1.0.28.aarch64-linux-gnu.tar.gz"
[[libsndfile]]
arch = "x86_64"
git-tree-sha1 = "c3ce59f30ee093ef6c5aa5738aded29d6d10100c"
os = "freebsd"

    [[libsndfile.download]]
    sha256 = "9bea12e32641ca770cd53724c2bd82253a77e43fb121c525a5e293da510e9d92"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.28+1/libsndfile.v1.0.28.x86_64-unknown-freebsd11.1.tar.gz"
[[libsndfile]]
arch = "x86_64"
git-tree-sha1 = "b0286e48305c5150872d54529a192ae7dcaa5f37"
libc = "musl"
os = "linux"

    [[libsndfile.download]]
    sha256 = "e377dd887b3386063b9488dce75e3c058af2d839a9c8e2ff67d166883eaa0a45"
    url = "https://github.com/JuliaBinaryWrappers/libsndfile_jll.jl/releases/download/libsndfile-v1.0.28+1/libsndfile.v1.0.28.x86_64-linux-musl.tar.gz"
